opcao =0
while opcao != 5:
    print("====Cardápio====")
    print("1- hambúrguer")
    print("2- pizza")
    print("3- salada")
    print("4- refrigerante")
    print("5- sair")
    opcao = int(input("Escolha uma opção"))
    if opcao ==1:
        print("Você escolheu hambúrguer")
    elif opcao ==2:
        print ("Você escolheu pizza")
    elif opcao ==3:
        print("Você escolheu salada")
    elif opcao ==4:
        print ("Você escolheu refrigerante")
    elif opcao ==5:
        print("Você escolheu sair")
        break
      
      